import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ContextWrapper from "@/components/ContextWrapper";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={"h-full " + inter.className}>
        <ContextWrapper>
          <div className="flex h-full flex-col">
            <Header></Header>
            <main className="grow ">{children}</main>
            <Footer></Footer>
          </div>
        </ContextWrapper>
      </body>
    </html>
  );
}
